# Generated by Django 4.2.5 on 2026-08-06 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=60)),
            ],
            options={
                'verbose_name': 'سلة',
                'verbose_name_plural': 'السلال',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الرمز')),
                ('percent_off', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الخصم %')),
                ('amount_off', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم ثابت')),
                ('min_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='أقل مبلغ للطلب')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = بلا حد', verbose_name='حد الاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الدفع'), ('paid', 'مدفوع'), ('processing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى'), ('refunded', 'مسترجع')], default='pending', max_length=12, verbose_name='الحالة')),
                ('payment_method', models.CharField(choices=[('card', 'بطاقة مدى / ائتمانية'), ('cod', 'الدفع عند الاستلام'), ('transfer', 'تحويل بنكي')], max_length=10, verbose_name='طريقة الدفع')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(max_length=20, verbose_name='الجوال')),
                ('city', models.CharField(max_length=60, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='الحي')),
                ('street', models.CharField(max_length=200, verbose_name='العنوان')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='الرمز البريدي')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='ملاحظات')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ضريبة القيمة المضافة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الشحن')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('tracking_number', models.CharField(blank=True, max_length=60, verbose_name='رقم الشحنة')),
                ('stock_released', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'قيد التنفيذ'), ('succeeded', 'ناجحة'), ('failed', 'فاشلة'), ('refunded', 'مستردة')], default='initiated', max_length=12)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'بند طلب',
                'verbose_name_plural': 'بنود الطلبات',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='orders_orde_number_539d36_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
