# Generated by Django 4.2.5 on 2026-08-06 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المورّد')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='الرقم الضريبي')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='العنوان')),
                ('payment_terms', models.CharField(blank=True, default='صافي 30 يوم', max_length=100, verbose_name='شروط الدفع')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مورّد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الأمر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('ordered', 'مُرسَل للمورّد'), ('received', 'مستلَم'), ('cancelled', 'ملغى')], default='draft', max_length=12, verbose_name='الحالة')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الأمر')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد المتوقع')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم فاتورة المورّد')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchasing.supplier', verbose_name='المورّد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'بند شراء',
                'verbose_name_plural': 'بنود الشراء',
            },
        ),
    ]
