# Generated by Django 4.2.5 on 2026-08-06 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المستودع')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='العنوان')),
                ('is_default', models.BooleanField(default=False, verbose_name='المستودع الافتراضي')),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'إدخال (شراء)'), ('out', 'إخراج (بيع)'), ('return', 'مرتجع'), ('adjust', 'تسوية جرد'), ('t_out', 'تحويل صادر'), ('t_in', 'تحويل وارد'), ('damage', 'تالف')], max_length=10, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(help_text='موجبة دائماً؛ الاتجاه يحدده نوع الحركة', verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='المرجع')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية')),
                ('reserved', models.IntegerField(default=0, verbose_name='محجوز لطلبات')),
                ('reorder_level', models.PositiveIntegerField(default=5, verbose_name='حد إعادة الطلب')),
                ('shelf', models.CharField(blank=True, max_length=40, verbose_name='موقع الرف')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
                'ordering': ['product__name'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
