# Generated by Django 4.2.5 on 2026-08-06 22:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='الشعار')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='بلد المنشأ')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='bi-plug', max_length=50, verbose_name='رمز (bootstrap-icon)')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='صورة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='رمز المنتج SKU')),
                ('barcode', models.CharField(blank=True, max_length=40, verbose_name='الباركود')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف الكامل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر قبل الخصم')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر التكلفة')),
                ('power_watt', models.PositiveIntegerField(blank=True, null=True, verbose_name='القدرة (واط)')),
                ('voltage', models.CharField(default='220V / 60Hz', max_length=30, verbose_name='الجهد')),
                ('energy_rating', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=5, verbose_name='كفاءة الطاقة')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='الضمان بالأشهر')),
                ('capacity', models.CharField(blank=True, help_text='مثال: 18 قدم، 12000 وحدة', max_length=60, verbose_name='السعة')),
                ('dimensions', models.CharField(blank=True, max_length=80, verbose_name='الأبعاد')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الوزن (كجم)')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='مواصفات إضافية')),
                ('is_active', models.BooleanField(default=True, verbose_name='معروض في المتجر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميّز في الرئيسية')),
                ('requires_installation', models.BooleanField(default=False, verbose_name='يحتاج تركيباً')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='العلامة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف')),
                ('wishlisted_by', models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='قائمة الرغبات')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='رأيك')),
                ('is_approved', models.BooleanField(default=False, verbose_name='منشور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_ed6a39_idx'),
        ),
    ]
